[package]
name = "white-horse-tables"
version = "0.0.1"
edition = "2021"

[dependencies]
csv = "1.3.0"
dollars = "0.0.1"
env_logger = "0.11.5"
error-chain = "0.12.4"
log = "0.4.22"
serde = { version = "1.0.207", features = ["derive"] }
tinyfiledialogs = "3.9.1"
