[package]
name = "white_horse_tables"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
dollars = "0.0.1"
serde = { version = "1.0.207", features = ["derive"] }
tinyfiledialogs = "3.9.1"
