[package]
name = "wh_api"
version = "0.0.1"
edition = "2021"

[dependencies]
wh_shared_lib = { path = "../wh_shared_lib" }
csv = "1.3.0"
dollars = "0.0.1"
serde = { version = "1.0.207", features = ["derive"] }
